import os
ELMO_MODEL_OPTIONS = os.getenv('ELMO_MODEL_OPTIONS')
ELMO_MODEL_WEIGHTS = os.getenv('ELMO_MODEL_WEIGHTS')
FASTTEXT_MODEL = os.getenv('FASTTEXT_MODEL')
PREDICTION_MODEL = os.getenv('PREDICTION_MODEL')

NER_KEY = 'ner'
