batch_size: 20

model:
  name: 'relextr_model.pt'

mlflow:
  tracking_uri: 'http://10.17.50.132:8080'
  experiment_name: 'no_exp'
  tags:
    files: 81, 82, 83
#    domain_out: 83

#vectorizer:
#  type: 'sent2vec'
#  model: './data/sent2vec/kgr10.bin'
#
#vectorizer:
#  type: 'fasttext'
#  model: './data/fasttext/kgr10.plain.lemma.skipgram.dim300.neg10.bin'

vectorizer:
  type: 'elmoconv'
  model: ''
