batch_size: 20
epochs: 30

model:
  name: 'relextr_model.pt'

mlflow:
  tracking_uri: 'http://10.17.50.132:8080'
  experiment_name: 'ner'
  tags:
    files: 81, 82, 83
    method: elmoconv
    domain_out: 83

#vectorizer:
#  type: ''
#  model: ''
#
#vectorizer:
#  type: 'sent2vec'
#  model: './data/sent2vec/kgr10.bin'
#
#vectorizer:
#  type: 'fasttext'
#  model: './data/fasttext/kgr10.plain.lemma.skipgram.dim300.neg10.bin'

vectorizer:
  type: 'elmoconv'
  model: ''

  #vectorizer:
  #type: 'ner'
  #model: ''
