IN_DOMAIN_KEY = 'in_domain'
OUT_DOMAIN_KEY = 'out_domain'
LEXICAL_SPLIT_KEY = 'lexical_split'
METHODS_KEY = 'methods'

SPERT_RUNS = {
    0: {LEXICAL_SPLIT_KEY: False},
    1: {LEXICAL_SPLIT_KEY: True},
    2: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False},
    3: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True},
    4: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False},
    5: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True},
    6: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False},
    7: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True}
}

DEFAULT_RUNS = {
    # all domains
    1001: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    1002: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    1003: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1004: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    1005: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1006: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    1007: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    1008: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    1009: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1010: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    1011: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1012: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    # in domain 112
    1013: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    1014: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    1015: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1016: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    1017: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1018: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    1019: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    1020: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    1021: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1022: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    1023: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1024: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    # in domain 114
    1025: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    1026: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    1027: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1028: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    1029: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1030: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    1031: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    1032: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    1033: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1034: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    1035: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1036: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    # in domain 115
    1037: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    1038: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    1039: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1040: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    1041: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1042: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    1043: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    1044: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    1045: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    1046: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    1047: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    1048: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},

    # # out domain 112
    # 1050: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo']},
    # 1051: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext']},
    # 1052: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'sent2vec']},
    # 1053: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit']},
    # 1054: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    # 1055: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    #
    # # out domain 114
    # 1056: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo']},
    # 1057: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext']},
    # 1058: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'sent2vec']},
    # 1059: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit']},
    # 1060: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    # 1061: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    #
    # # out domain 115
    # 1062: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo']},
    # 1063: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext']},
    # 1064: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'sent2vec']},
    # 1065: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit']},
    # 1066: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    # 1067: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
    # METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

ALL_DOMAINS = {
    # all domains
    2001: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    2002: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    2003: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    2004: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    2005: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},

    2006: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    2007: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    2008: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    2009: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    2010: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},

    2011: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    2012: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    2013: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    2014: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    2015: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},

    2016: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    2017: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    2018: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    2019: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    2020: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},

    2021: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    2022: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    2023: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    2024: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    2025: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    2026: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    2027: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    2028: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    2029: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    2030: {LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

ALL_DOMAINS_LEXICAL = {
    3001: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    3002: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    3003: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    3004: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    3005: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},

    3006: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    3007: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    3008: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    3009: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    3010: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},

    3011: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    3012: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    3013: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    3014: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    3015: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},

    3016: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    3017: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    3018: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    3019: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    3020: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},

    3021: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    3022: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    3023: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    3024: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    3025: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    3026: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    3027: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    3028: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    3029: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    3030: {LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_LEXICAL_112 = {
    4001: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    4002: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    4003: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    4004: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    4005: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},

    4006: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    4007: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    4008: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    4009: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    4010: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},

    4011: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    4012: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    4013: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    4014: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    4015: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},

    4016: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    4017: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    4018: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    4019: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    4020: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},

    4021: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    4022: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    4023: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    4024: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    4025: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    4026: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    4027: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    4028: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    4029: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    4030: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_LEXICAL_114 = {
    5001: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    5002: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    5003: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    5004: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    5005: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},

    5006: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    5007: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    5008: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    5009: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    5010: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},

    5011: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    5012: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    5013: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    5014: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    5015: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},

    5016: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    5017: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    5018: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    5019: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    5020: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},

    5021: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    5022: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    5023: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    5024: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    5025: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    5026: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    5027: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    5028: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    5029: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    5030: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_LEXICAL_115 = {
    6001: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    6002: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    6003: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    6004: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},
    6005: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo']},

    6006: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    6007: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    6008: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    6009: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},
    6010: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext']},

    6011: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    6012: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    6013: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    6014: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},
    6015: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'sent2vec']},

    6016: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    6017: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    6018: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    6019: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},
    6020: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit']},

    6021: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    6022: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    6023: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    6024: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    6025: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    6026: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    6027: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    6028: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    6029: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    6030: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: True,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_112 = {
    7001: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    7002: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    7003: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    7004: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    7005: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},

    7006: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    7007: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    7008: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    7009: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    7010: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},

    7011: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    7012: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    7013: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    7014: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    7015: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},

    7016: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    7017: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    7018: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    7019: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    7020: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},

    7021: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    7022: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    7023: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    7024: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    7025: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    7026: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    7027: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    7028: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    7029: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    7030: {IN_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_114 = {
    8001: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    8002: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    8003: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    8004: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    8005: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},

    8006: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    8007: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    8008: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    8009: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    8010: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},

    8011: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    8012: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    8013: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    8014: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    8015: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},

    8016: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    8017: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    8018: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    8019: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    8020: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},

    8021: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    8022: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    8023: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    8024: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    8025: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    8026: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    8027: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    8028: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    8029: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    8030: {IN_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

IN_DOMAIN_115 = {
    9001: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    9002: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    9003: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    9004: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},
    9005: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo']},

    9006: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    9007: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    9008: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    9009: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},
    9010: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext']},

    9011: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    9012: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    9013: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    9014: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},
    9015: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'sent2vec']},

    9016: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    9017: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    9018: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    9019: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},
    9020: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit']},

    9021: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    9022: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    9023: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    9024: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    9025: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},

    9026: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    9027: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    9028: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    9029: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
    9030: {IN_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
           METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

OUT_DOMAIN_112 = {
    # out domain 112
    10001: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo']},
    10002: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext']},
    10003: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'sent2vec']},
    10004: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit']},
    10005: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    10006: {OUT_DOMAIN_KEY: '112', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

OUT_DOMAIN_114 = {
    # out domain 114
    20001: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo']},
    20002: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext']},
    20003: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'sent2vec']},
    20004: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit']},
    20005: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    20006: {OUT_DOMAIN_KEY: '114', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

OUT_DOMAIN_115 = {
    # out domain 115
    30001: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo']},
    30002: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext']},
    30003: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'sent2vec']},
    30004: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit']},
    30005: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'fasttext', 'sent2vec']},
    30006: {OUT_DOMAIN_KEY: '115', LEXICAL_SPLIT_KEY: False,
            METHODS_KEY: ['elmo', 'retrofit', 'sent2vec']},
}

RUNS = {
    'spert': SPERT_RUNS,
    'default': DEFAULT_RUNS,
    'all': ALL_DOMAINS,
    'all_lexical': ALL_DOMAINS_LEXICAL,
    '112_in_lexical': IN_DOMAIN_LEXICAL_112,
    '114_in_lexical': IN_DOMAIN_LEXICAL_114,
    '115_in_lexical': IN_DOMAIN_LEXICAL_115,
    '112_in': IN_DOMAIN_112,
    '114_in': IN_DOMAIN_114,
    '115_in': IN_DOMAIN_115,
    '112_out': OUT_DOMAIN_112,
    '114_out': OUT_DOMAIN_114,
    '115_out': OUT_DOMAIN_115,
}
