mlflow:
  tracking_uri: 'http://10.17.50.132:8080'
  experiment_name: 'LREC_dropout_test'

keys: 'keys.txt'

# set it to BS * #number_of_devices (nn.DataParallel)
batch_size: 100
epochs: 50
runs: '115_in_lexical'
