batch_size: 20
epochs: 30

model:
  name: 'relextr_model.pt'

mlflow:
  tracking_uri: 'http://10.17.50.132:8080'
  experiment_name: 'LREC'
  tags:
    files: 111, 113, 115
    lexical_split: 'no'
    domain_out: 'no'

dataset: all

keys: 'keys.txt'
vectorizers:
  - 'elmo.rel.pt'
  - 'fasttext.rel.pt'
  - 'retrofit.rel.pt'
