batch_size: 20
epochs: 30

mlflow:
  tracking_uri: 'http://10.17.50.132:8080'
  experiment_name: 'LREC_4'
  tags:
    files: 112, 114, 115

keys: 'keys.txt'

model:
  name: '115_out.pt'
runs: '115_out'
